### ISSUE TITLE
In a single player game, typing commands or chatting will make errors

### ISSUE THREAD

**Issue by PeterFujiyu** [lushangkan/AutoLogin#1]
[14:37:23] [Render thread/ERROR]: Error executing task on Client
net.minecraft.class_148: Main thread packet handler
	at net.minecraft.class_2600.method_11072(class_2600.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.mixinextras$bridge$method_18859$5(class_4093.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.wrapOperation$dai000$carpet-tis-addition$yeetUpdateSuppressionCrash_implForThreadExecutorTaskExecuting(class_4093.java:570) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[1.20.4fab.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "cn.cutemc.autologin.records.ServerStatus.isLogin()" because "cn.cutemc.autologin.AutoLogin.server" is null
	at cn.cutemc.autologin.listeners.SystemMsgListener.onReceiveGameMessage(SystemMsgListener.java:34) ~[AutoLogin-0.1.1.jar:?]
	at net.fabricmc.fabric.api.client.message.v1.ClientReceiveMessageEvents.lambda$static$8(ClientReceiveMessageEvents.java:124) ~[fabric-message-api-v1-6.0.6+78d798af4f-be4a4960cdccb456.jar:?]
	at net.minecraft.class_7594.localvar$dpi000$fabric-message-api-v1$fabric_modifyGameMessage(class_7594.java:1080) ~[client-intermediary.jar:?]
	at net.minecraft.class_7594.method_44736(class_7594.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_43596(class_634.java:869) ~[client-intermediary.jar:?]
	at net.minecraft.class_7439.method_43631(class_7439.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_7439.method_11054(class_7439.java:7) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[client-intermediary.jar:?]
	... 12 more

**Comment by PeterFujiyu** [comment]
[autologin.json](https://github.com/user-attachments/files/16201183/autologin.json)

**Comment by PeterFujiyu** [comment]
{
  "mainToggle": true,
  "serverAddresses": "**cs*****er.t***",
  "password": "******",
  "promptRequireLogin": "*****",
  "promptRequireRegister": "******",
  "loginCommand": "/l %p",
  "registerCommand": "/reg %p %p"
}

**Comment by lushangkan** [comment]
I'll fix this when I'm in good shape, thanks for contributing to the project!
